---
development:
  projects:
    - name: foo
      arch:
        - esp32
        - esp32s1
      path: dist/foo
      stable_version: 2.0.0
      beta_nodes:
        - aa:bb:cc:dd:ee:ff
    - name: bar
      path: dist/bar
      arch:
        - esp8266
    - name: buz
      arch:
        - esp32
        - esp8266
      path: dist/buz
test:
  projects:
    - name: foo
      arch:
        - esp32
        - esp32s1
      path: dist/foo
      stable_version: 2.0.0
      beta_nodes:
        - aa:bb:cc:dd:ee:ff
    - name: bar
      path: dist/bar
      arch:
        - esp8266
    - name: buz
      arch:
        - esp32
        - esp8266
      path: dist/buz
