---
name: Build
on:
  - pull_request
  - push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # use a single version in matrix for python, nodejs and ruby because
        # the subject of the job is style of code, not the code itself.
        python:
          - 3.7
        ruby:
          - 2.6
        node-version:
          - 12.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt

      - name: Install bundler
        run: |
          gem install bundler
          bundler --version
          bundler config path vendor/bundle
          bundler config

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install dependencies with bunlder
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run rubocop
        run: |
          bundle exec rake rubocop

      - name: Run yamllint
        run: |
          yamllint -v
          bundle exec rake yamllint

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          yarn --version
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install nodejs modules with yarn
        run: |
          yarn --frozen-lockfile

      - name: Run markdownlint
        run: |
          bundle exec rake markdownlint

  build:
    name: Run rspec (ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler
        run: |
          gem install bundler
          bundler --version
          bundler config path vendor/bundle
          bundler config

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install dependencies with bunlder
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run rspec
        run: |
          bundle exec rake spec
