---
name: Build
on:
  - pull_request
  - push
jobs:
  build:
    name: Ruby version ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler
        run: |
          gem install bundler
          bundler --version
          bundler config

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install dependencies with bunlder
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run rubocop
        run: |
          bundle exec rake rubocop

      - name: Run rspec
        run: |
          bundle exec rake spec
